### ISSUE TITLE
Validasi TLDs 

### ISSUE THREAD

**Issue by ngadmini** [alsyundawy/dnstrust-apjii#2]
Halo bro @alsyundawy 
[Mungkin script ini](https://gist.github.com/ngadmini/8bcabcb0b31f02619e7b638065621f75) berguna untuk memeriksa invalid **Top Level Domain** pada file [db_trustpositif.txt](https://github.com/alsyundawy/dnstrust-apjii/blob/main/raw/db_trustpositif.txt)
```
ngadimin@Q4OS:~/Documents/RPZ_arsip/tlds$ ./tlds_validation.sh        

[INFO] starting TLDs validation, target: db_trustpositif.txt
[INFO] there are 2 dir. please removing the older: tld.qgFS
do you want to remove it's ? [Y/n] y
[INFO] removing dir: tld.qgFS
[INFO] check availability remote files
[INFO] identifying invalid TLDs
[INFO] there are 182 invalid TLDs
[INFO] there are NO change in invalid TLDs
[HINT] please check dir tld.Rxq5 for complete result
bye!

ngadimin@Q4OS:~/Documents/RPZ_arsip/tlds$
```

Best Regards,
nGadmini nGadimin

**Comment by alsyundawy** [comment]
tlds_validation.sh: 22: Bad substitution
tlds_validation.sh: 50: Syntax error: redirection unexpected

**Comment by ngadmini** [comment]
> tlds_validation.sh: 22: Bad substitution tlds_validation.sh: 50: Syntax error: redirection unexpected

Terimakasih,
saya coba hasilnya **ok**, coba anda update script-nya ke [latest-version](https://gist.githubusercontent.com/ngadmini/8bcabcb0b31f02619e7b638065621f75/raw/a4090b8c251382e1bd926f012a1c7a544e15426f/tlds_validation.sh). 

```
ngadimin@Q4OS:~/Documents/test$ ./tlds_validation.sh 

[INFO] starting TLDs validation, target: db_trustpositif.txt
[INFO] check availability remote files
[INFO] identifying invalid TLDs
[INFO] there are 185 invalid TLDs
[INFO] there are NO change in invalid TLDs
[HINT] please check dir tld.Zc57 for complete result
bye!

ngadimin@Q4OS:~/Documents/test$
```

**Comment by alsyundawy** [comment]
oot@blackbox:~# neofetch
..............                                     root@blackbox
            ..,;:ccc,.                             -------------
          ......''';lxO.                           OS: Kali GNU/Linux Rolling x86_64
.....''''..........,:ld;                           Host: VMware Virtual Platform None
           .';;;:::;,,.x,                          Kernel: 6.0.0-kali6-amd64
      ..'''.            0Xxoc:,.  ...              Uptime: 13 hours, 36 mins
  ....                ,ONkc;,;cokOdc',.            Packages: 1101 (dpkg)
 .                   OMo           ':ddo.          Shell: bash 5.2.15
                    dMc               :OO;         Resolution: 800x600
                    0M.                 .:o.       Terminal: /dev/pts/0
                    ;Wd                            CPU: Intel Xeon E5-2650 v2 (8) @ 2.599GHz
                     ;XO,                          GPU: 00:0f.0 VMware SVGA II Adapter
                       ,d0Odlc;,..                 Memory: 220MiB / 15998MiB
                           ..',;:cdOOd::,.
                                    .:d;.':;.
                                       'd,  .'
                                         ;l   ..
                                          .o
                                            c
                                            .'
                                             .

root@blackbox:~# sh tlds_validation.sh
tlds_validation.sh: 22: Bad substitution
tlds_validation.sh: 50: Syntax error: redirection unexpected
