### ISSUE TITLE
enscrypted

### ISSUE THREAD

**Issue by ngadmini** [alsyundawy/dnstrust-apjii#5]
Pagi bro,

Yang ini kok pakai **wildcard** bro ?

> https://github.com/alsyundawy/dnstrust-apjii/blob/01e8497cbc57b6db4dd2c824ee02f102b7675eeb/raw/db_trustpositif.txt

regards
nGadmini binti nGadimin

**Comment by alsyundawy** [comment]
jawabannya ada disini

![image](https://user-images.githubusercontent.com/6451849/223601773-e8033247-6279-4fe6-8651-50669cb7585f.png)

silahkan download di https://trustpositif.kominfo.go.id/assets/db/domains
